### ISSUE TITLE
[TODO] subject の必須項目 list

### ISSUE THREAD

**Issue by habvi** [s1-haya/webserv#12]
## mandatory
- [x] Makefile : `$(NAME), all, clean, fclean, and re`
- [x] compile : `c++ -Wall -Wextra -Werror -std=c++98`
- [x] Program name : `webserv`
- [x] Turn in files  : `Makefile`, `*.{h, hpp}`, `*.cpp`, `*.tpp`, `*.ipp`, `configuration files`
- [x] 実行：`./webserv [configuration file]`
  - [x] argc error?

## requirements
- [x] `config file` を引数として受け取るか、`default path` を使用
- [x] 他の web server を実行しない
- [x] server は block してはいけない。client の処理を適切に処理
- [x] `poll() (or同等の)`
  - [x] `non-blocking`。client と server 間の全ての I/O 操作に対して 1 つの `poll() (or同等の)` のみ使う
  - [x] read, write を同時にチェックする
  - [x] `poll() (or同等の)` を通さず read, write しない
  - [x] read, write の後に errno の値を見てはいけない
  - [x] config file 読み込む前に `poll() (or同等の)` を使う必要はない
  - [x] どの non-blocking な fd に対しても `poll() (or同等の)` を使わずに `read/recv or write/send` してたら 0 点
- [x] server
  - [x] これらのマクロ使って ok (`FD_SET`, `FD_CLR`, `FD_ISSET`, `FD_ZERO`)
  - [x] request は無限の待機状態に陥らない ->  timeout 設定
  - [x] 選択した web browser と互換性がある -> firefox
  - [x] HTTP1.1 に準拠してる nginx (？) は、header と応答の動作を比較するために使用できる
  - [x] `default error pages` が提供されていない場合、server は `default error pages` を持つ必要がある
  - [x]  HTTP response の status code は正確に
  - [x] `CGI` のための `fork` 使用以外で `fork` を使用しない
  - [x] `a fully static website` を提供できる必要がある
  - [x] client はファイルアップロードできる必要がある
  - [x] 少なくとも `GET`, `POST`, `DELETE` メソッドが必要
  - [x] server へのストレステストを行う。どんな状況でも利用可能な状態を維持する。停止しないように。
  - [x] 複数の port を listen できる必要がある (config file を参照)
- [x] Your server should never die. -> crach や予期せぬエラーでの終了はダメという意味か？

## config file
- [x] 各 server で `port`, `host` を選択できるようにする
- [x] `server_name` を設定する/しないができる
- [x] `host:port` に対して最初の server が default server になる (他の server に属さない全てのリクエストに応答する)
- [x] `defualt error pages` を設定する
- [x] client の `body size` を制限する
- [x] 以下のルール/設定の内 1 つまたは複数を持つ root を設定する (root は正規表現を使用しない)
  - [x]  root に対して受け入れられる HTTP method のリストを定義する
  - [x] `HTTP redirect` を定義する
  - [x] ファイル検索をするディレクトリ/ファイルを定義する -> alias？
  - [x] `directory listing` を on/off する -> `autoindex`
  - [x] リクエストがディレクトリの場合に、応答する `default file` を設定
  - [x] 特定のファイル拡張子に基づいて `CGI` を実行
  - [x] `POST`, `GET` method で動作するように
  - [x] アップロードされたファイルを受け入れ、それらの保存場所を設定できるように
    - [x] CGI を直接呼ばないため、full path を `SCRIPT_NAME` とする
    - [x] chunked request の場合、server はそれを unchunk し、CGI は body の終了として `EOF` を期待する
    - [x] CIG の出力も同様に、CGI から `content_length` が返されない場合、`EOF` が返されたデータの終了を示す
    - [x] プログラムは要求されたファイルを最初の引数として CGI を呼び出す
    - [ ] CGI は相対パスのファイルアクセスに対して、正しいディレクトリで実行される必要がある
    - [x] server は 1 つの CGI で動作する必要がある

## test
- [x] 全ての機能が動作することを実証するための設定ファイル, 基本的なファイル, テスト
- [x] 1 つのプログラムでのみテストするのではなく、Python, Go, C, C++ などで書く

## bonus (余裕があれば)
- [ ] cookies & session
- [x] 複数 CGI
