### ISSUE TITLE
[add] Lexerの機能追加

### ISSUE THREAD

**Issue by eito2002** [s1-haya/webserv#145]
### Done
- [x] 現在はserver, server_name, listen, location, root, indexに対応

### TODO
- [ ] locationの中にあるlocation(nginxではok)
- [x] 複数のserver_name
- [x] server_nameのデフォルト
- [ ] portのパラメータのバリデーション
- [x] default error pages
- [x] client body size
- [x] accepted HTTP methods
- [x] HTTP redirection
- [x] Turn on or off directory listing
- [ ] CGI関連のディレクティブ
- [x] server_name location, server_name server_name
- [ ] クォーテーション

ベタ打ちの"server_name"等
